const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const hljsDir = path.join(root, 'node_modules/highlight.js/lib');
const outFile = path.join(root, 'renderer', 'hljs.js');

const coreSrc = fs.readFileSync(path.join(hljsDir, 'core.js'), 'utf8');

const langs = [
  'bash', 'c', 'cpp', 'csharp', 'css', 'diff', 'go', 'ini', 'java',
  'javascript', 'json', 'kotlin', 'markdown', 'python', 'rust', 'sql',
  'typescript', 'xml', 'yaml', 'php', 'ruby', 'swift', 'shell',
  'dockerfile', 'makefile'
];

const registrations = langs.map((name) => {
  const src = fs.readFileSync(path.join(hljsDir, 'languages', name + '.js'), 'utf8');
  return `  function reg_${name.replace(/[^a-z0-9]/gi, '_')}() {\n    const module = { exports: {} };\n${indent(src, '    ')}\n    return module.exports;\n  }\n  hljs.registerLanguage(${JSON.stringify(name)}, reg_${name.replace(/[^a-z0-9]/gi, '_')}());`;
}).join('\n');

function indent(str, pad) {
  return str.split('\n').map(l => pad + l).join('\n');
}

const bundle = `/* Generated by scripts/build-hljs.cjs — do not edit by hand. */
(function () {
  'use strict';
  const module = { exports: {} };
${indent(coreSrc, '  ')}
  const hljs = module.exports;

${registrations}

  hljs.configure({ ignoreUnescapedHTML: true });
  window.hljs = hljs;
})();
`;

fs.writeFileSync(outFile, bundle);
console.log('wrote', outFile, bundle.length, 'bytes,', langs.length, 'languages');
